<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_bantuan_semua_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    // tahun
    function get_tahun_all()
    {
        $table = 't_tahun';
        $id = 'id_tahun';
        $order_by = 'tahun';
        $order = 'DESC';
        $this->db->order_by($order_by, $order);
        return $this->db->get($table)->result();
    }

    function get_tahun_by_id($id)
    {
        $table = 't_tahun';
        $this->db->where($id);
        return $this->db->get($table)->row();
    }

}

/* End of file T_tahun_model.php */
/* Location: ./application/models/T_tahun_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-20 09:06:29 */
/* http://harviacode.com */